#!/bin/sh
root_dir="`git rev-parse --git-dir`/.."
cd $root_dir
excludes=""
if [ -f .tagskip ]; then
    for exclude in $(cat .tagskip); do
        excludes="$excludes | grep -v '${exclude}'"
    done
fi

# NOTE: if you get some error about `-e` not being supported
# you may have to explicitly install ctags (apt-get install ctags)
# https://stackoverflow.com/questions/2580313/ctags-doesnt-understand-e-option-no-exuberant-tags-option
eval "git ls-files $excludes | ctags -e -L -"
